;             
CREATE USER IF NOT EXISTS H2 SALT '599ae575eaf8ad89' HASH '6a0d965158ecad2aa591136a1646833e981be6cf3805f5d25686cecc3e875488' ADMIN;           
CREATE SEQUENCE PUBLIC.HIBERNATE_SEQUENCE START WITH 4;       
CREATE CACHED TABLE PUBLIC.AUTHOR(
    ID BIGINT NOT NULL,
    NAME VARCHAR(255)
);        
ALTER TABLE PUBLIC.AUTHOR ADD CONSTRAINT PUBLIC.CONSTRAINT_7 PRIMARY KEY(ID); 
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.AUTHOR;  
INSERT INTO PUBLIC.AUTHOR(ID, NAME) VALUES
(1, 'Robert Martin'),
(2, 'Martin Fowler'),
(3, 'Donald Knuth');
CREATE CACHED TABLE PUBLIC.BOOK(
    ID BIGINT NOT NULL,
    TITLE VARCHAR(255),
    AUTHOR_ID BIGINT
);  
ALTER TABLE PUBLIC.BOOK ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(ID);   
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.BOOK;    
ALTER TABLE PUBLIC.BOOK ADD CONSTRAINT PUBLIC.FKKLNRV3WELER2FTKWEEWLKY958 FOREIGN KEY(AUTHOR_ID) REFERENCES PUBLIC.AUTHOR(ID) NOCHECK;        
