DROP TABLE IF EXISTS AUTHOR;
DROP TABLE IF EXISTS BOOK;

CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 4;

CREATE TABLE AUTHOR(
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(255)
);

INSERT INTO AUTHOR(ID, NAME) VALUES
(1, 'Robert Martin'),
(2, 'Martin Fowler'),
(3, 'Donald Knuth');

CREATE TABLE BOOK(
    ID BIGINT PRIMARY KEY,
    TITLE VARCHAR(255),
    AUTHOR_ID BIGINT,
    FOREIGN KEY(AUTHOR_ID) REFERENCES AUTHOR(ID)
);
